name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  
          cache: 'npm'         

      - name: Install Dependencies
        run: npm install

      - name: Setup .env.production
        run: |
          echo "VITE_BASE_URL=/FlatEarthProject/" > .env.production

      - name: Build Application
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.TOKEN }} 
        run: npm run deploy
